### ISSUE TITLE
add git-lfs to the container

### ISSUE THREAD

**Issue by kistlin** [crops/yocto-dockerfiles#58] opened 2021-11-20 06:43 UTC
Recently I used `crops/poky-container` to build a custom Linux using Yocto and the repo tool. (I pulled it from docker hub `crops/poky`)

During fetching of the sources it failed, because git-lfs was not installed. This would complement #22.

**Comment by kistlin** [comment] 2021-11-20 15:02
Well it looks like this is eventually done in #40.

**Comment by moto-timo** [comment] 2022-01-06 15:54
Closing as duplicate of #40.

**Closed by moto-timo** 2022-01-06 15:54 UTC
